### ISSUE TITLE
数据库前缀是否写死

### ISSUE THREAD

**Issue by coruni** [daocatt/flarum-ext-checkin#2]
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.user_checkin_history'

错误日志中出现 'flarum.user_checkin_history' 但是我的数据库前缀是fl_ 实际上应该是'flarum.fl_user_checkin_history'

**Comment by coruni** [comment]
与错误日志

Warning: Undefined array key "data" in /www/wwwroot/xxxx.com/vendor/flarum/core/src/Frontend/Content/CorePayload.php on line 57

Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /www/wwwroot/xxxx.com/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:20 Stack trace: #0 /www/wwwroot/xxxx.com/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(42): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent() #1 /www/wwwroot/xxxx.com/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(21): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput() #2 /www/wwwroot/xxxx.com/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(75): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit() #3 /www/wwwroot/xxxx.com/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run() #4 /www/wwwroot/xxxx.com/public/index.php(26): Flarum\Http\Server->listen() #5 {main} thrown in /www/wwwroot/xxxx.com/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php on line 20

**Comment by nodeloc** [comment]
应该是没有加前缀
`https://github.com/daocatt/flarum-ext-checkin/blob/main/src/Listeners/CheckinListener.php`
这里写死了，可以自己加个前缀

**Comment by daocatt** [comment]
更新查看：
https://github.com/daocatt/flarum-ext-checkin/commit/27ddb3fb4e46f83ac8108c79114f475dc7493d10
