### ISSUE TITLE
与antoinefr/flarum-ext-money冲突，依赖了别的扩展需要依赖antoinefr/flarum-ext-money该怎么解决。

### ISSUE THREAD

**Issue by Quan-Min** [daocatt/flarum-ext-checkin#3]
我安装了其他的库，依赖了antoinefr/flarum-ext-money。
导致与money-plus冲突了。  请问下我该怎么解决，感谢  给我个思路也行。 

我不知道 是否需要修改源码。  谢谢您的回复。

**Comment by daocatt** [comment]
你可以只选择其中一个就可以了。我这个是基于它那个的一些小修改。
